markdown: redcarpet
name: 18F Plain language tutorial 
exclude:
- CONTRIBUTING.md
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- go
- vendor

permalink: pretty
highlighter: rouge
incremental: true

sass:
  style: :compressed

# Author/Organization info to be displayed in the templates
author:
  name: 18F
  url: https://18f.gsa.gov

# Point the logo URL at a file in your repo or hosted elsewhere by your organization
logourl: /assets/img/18f-logo.png
logoalt: 18F logo

# To expand all navigation bar entries by default, set this property to true:
expand_nav: true

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Welcome
  internal: true
- text: Tutorial goals
  url: tutorial-goals/
  internal: true
- text: Introduction
  url: introduction/
  internal: true
- text: What is plain language?
  url: what-is-plain-language/
  internal: true
- text: Why is plain language important?
  url: why-is-plain-language-important/
  internal: true
- text: Legal considerations of plain language
  url: legal-considerations/
  internal: true
- text: "Strategies: How to write in plain language"
  url: strategies/
  internal: true
  children: 
  - text: "Strategy 1: Always think of your user"
    url: strategy-1/
    internal: true
  - text: "Strategy 2: Use the simplest word that will do"
    url: strategy-2/
    internal: true
  - text: "Strategy 3: Keep it short and sweet"
    url: strategy-3/
    internal: true
  - text: "Strategy 4: Cut to the chase (also known as the inverted pyramid structure)"
    url: strategy-4/
    internal: true
  - text: "Strategy 5: Use visuals"
    url: strategy-5/
    internal: true
  - text: "Strategy 6: If it’s broke, fix it"
    url: strategy-6/
    internal: true
- text: How can I tell if my content is in plain language?
  url: how-can-i-tell/
  internal: true
- text: Test your knowledge!
  url: test-your-knowledge/
  internal: true
  children:
  - text: "Activity 1: Privacy statement"
    url: privacy-statement/
    internal: true
  - text: "Activity 2: FAQs"
    url: faqs/
    internal: true
- text: There’s more to learn (additional resources)
  url: more-to-learn/
  internal: true


repos:
- name: 18F plain language tutorial
  description: Main repository
  url: https://github.com/18F/plain-language-tutorial

back_link:
  url: "https://pages.18f.gov/edu/"
  text: Return to 18F Edu

google_analytics_ua: UA-48605964-19

collections:
  pages:
    output: true
    permalink: /:path/

defaults:
- scope:
    path: ""
  values:
    layout: "guides_style_18f_default"

# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
